services:
  backend:
    build: .
    container_name: sih-backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - minio
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/sihdb
      - REDIS_URL=redis://redis:6379
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin

  postgres:
    image: postgres:15.2
    container_name: sih-postgres
    restart: always
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=sihdb
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2
    container_name: sih-redis
    restart: always
    environment:
      - REDIS_PASSWORD=redispass
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: sih-minio
    command: server /data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/data

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: sih-celery
    depends_on:
      - backend
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/sihdb
      - REDIS_URL=redis://redis:6379
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - .:/app
    restart: always
volumes:
  minio-data:

